### ISSUE TITLE
Persistence in docker compose

### ISSUE THREAD

**Issue by perelin** [seletskiy/firebase-emulator#4]
Hi,

I did not manage to persist the emulator data when using docker compose. Used a docker volume and added `--import=./<volume-name> --export-on-exit` to the `firebase emulators:start` command. On exiting docker compose with CTRL-C no data is exported.

Any ideas?

Regards, Sebastian

**Comment by amanfrinati** [comment]
Hi @perelin,

you just mount the `firebase` folder. I do this in my project:

```yaml
volumes:
  firebase-data:

services:
  firebase:
    build:
      context: https://github.com/seletskiy/firebase-emulator.git
    volumes:
      - firebase-data:/firebase
    ports:
      - "9199:9199"
      - "4000:4000"
```

During the stopping phase the `firebase emulators:export` command save the state in a `emulators.data` file.
